project_id = "jzigkamsoszicuekrzuq"

[functions.send-booking-confirmation]
verify_jwt = false

[functions.notify-booking-cancellation]
verify_jwt = false

[functions.send-employee-invite]
verify_jwt = false

[functions.notify-booking-message]
verify_jwt = false
